# Generated by Django 3.2.9 on 2021-11-24 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('image', models.ImageField(upload_to='images')),
                ('status', models.IntegerField(choices=[(1, 'Waiting'), (2, 'Running'), (3, 'Completed'), (-1, 'Failed')])),
                ('category', models.CharField(blank=True, help_text='This is the category with highest probability.', max_length=128)),
                ('probability', models.DecimalField(blank=True, decimal_places=3, max_digits=8)),
                ('raw_output', models.JSONField(blank=True, help_text='The raw output (with all possible categories) returned by GoogleNet.')),
            ],
        ),
    ]
