# Generated by Django 3.2.9 on 2021-11-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_alter_image_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='raw_output',
            field=models.TextField(blank=True, help_text='The raw output (with all possible categories) returned by GoogleNet.'),
        ),
    ]
